apiVersion: v1
kind: Secret
metadata:
  name: flux-secrets
  namespace: flux
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://flux_user:flux_prod_secure_password_123!@flux-postgres:5432/flux_db"
  POSTGRES_USER: "flux_user"
  POSTGRES_PASSWORD: "flux_prod_secure_password_123!"
  POSTGRES_DB: "flux_db"
  WEATHER_API_KEY: ""
  LLM_API_KEY: ""
